"""Torch-first utilities for rebuilding PCS-QCNN components."""

from qcnn.automation import (
    AutoTrainingConfig,
    AutoTrainingResult,
    MnistDatasetConfig,
    OptimizerConfig,
    OutputConfig,
    SeedConfig,
    SeedTrainingArtifacts,
    SeedTrainingRun,
    TrainingConfig,
    run_mnist_auto_training,
)
from qcnn.article import (
    ARTICLE_ALIGNED_BRIGHTNESS_RANGE,
    ARTICLE_ALIGNED_IMAGE_SIZE,
    ARTICLE_ALIGNED_SAMPLES_PER_CLASS,
    ENCODER_NORMALIZATION_MISMATCH,
    article_alignment_warnings,
    warn_for_article_alignment,
)
from qcnn.article_figures import (
    ARTICLE_PANEL_FIGSIZE,
    MetricHistorySummary,
    TemporalStatisticSummary,
    focus_metric_history,
    load_saved_parameter_stats_line,
    load_saved_training_histories,
    plot_temporal_summary,
    summarize_accuracy_histories,
    summarize_temporal_samples,
)
from qcnn.classic import ClassicalCNN, ClassicalMLP
from qcnn.data import PreparedMnistSplits, TensorImageDataset, prepare_mnist_splits
from qcnn.hybrid import PCSQCNN, PCSQCNNNoQFT
from qcnn.layout import (
    CANONICAL_TENSOR_CONTRACT,
    RegisterLayout2D,
    is_power_of_two,
    move_active_qubit_to_condition,
)
from qcnn.matplotlib_config import configure_matplotlib_pdf_fonts
from qcnn.model import EvaluationSummary, ImageClassifierRunner, TrainingHistory, accuracy_from_logits
from qcnn.model_spec import ModelSpec
from qcnn.quantum import (
    FiniteShotHistogram2D,
    FrqiEncoder2D,
    MarginalMeasurement2D,
    ModeMultiplexer2D,
    pauli_coefficients_to_unitary,
)
from qcnn.serialization import (
    AutoTrainingSnapshotBatchwiseLossSamplingEvaluation,
    AutoTrainingSnapshotBatchwiseShotBudgetEvaluation,
    AutoTrainingSnapshotEvaluationContext,
    AutoTrainingSnapshotLayerGradientNormsEvaluation,
    AutoTrainingSnapshotReadoutLandscapeEvaluation,
    AutoTrainingSnapshotReadoutEntropyEvaluation,
    AutoTrainingSnapshotRepeatedEvaluation,
    AutoTrainingSnapshotTestEvaluation,
    LoadedAutoTrainingRun,
    LoadedAutoTrainingRunEvaluationContext,
    LoadedAutoTrainingRunTestEvaluation,
    LoadedModelCheckpoint,
    compute_histogram_shannon_entropy,
    evaluate_auto_training_snapshot_layer_gradient_norms_on_saved_mnist_test,
    evaluate_auto_training_snapshot_batchwise_loss_sampling_on_saved_mnist_test,
    evaluate_auto_training_snapshot_readout_entropy_on_saved_mnist_test,
    evaluate_auto_training_snapshot_readout_landscape_on_saved_mnist_test,
    evaluate_auto_training_snapshot_repeated_on_saved_mnist_test,
    evaluate_auto_training_snapshot_on_saved_mnist_test,
    reconstruct_auto_training_snapshot_runner_and_test_loader,
    evaluate_loaded_auto_training_run_on_saved_mnist_test,
    format_nested_mapping_markdown,
    load_auto_training_run,
    load_model_checkpoint,
    reconstruct_run_runner_and_test_loader,
    reconstruct_saved_mnist_splits_from_run,
    resolve_snapshot_trainable_layer_blocks,
    save_model_checkpoint,
)
from qcnn.statistics import (
    AccuracyCollector,
    CrossEntropyLossCollector,
    LossCollector,
    StatisticBatchContext,
    StatisticCollector,
)
from qcnn.visualization import (
    ErrorAnalysisPayload,
    MisclassifiedExample,
    collect_error_analysis_payload,
    plot_convergence,
    plot_error_analysis,
    plot_error_analysis_payload,
)

__all__ = [
    "ARTICLE_ALIGNED_BRIGHTNESS_RANGE",
    "ARTICLE_ALIGNED_IMAGE_SIZE",
    "ARTICLE_ALIGNED_SAMPLES_PER_CLASS",
    "ARTICLE_PANEL_FIGSIZE",
    "AccuracyCollector",
    "AutoTrainingSnapshotBatchwiseLossSamplingEvaluation",
    "AutoTrainingSnapshotBatchwiseShotBudgetEvaluation",
    "AutoTrainingSnapshotEvaluationContext",
    "AutoTrainingSnapshotLayerGradientNormsEvaluation",
    "AutoTrainingSnapshotReadoutLandscapeEvaluation",
    "AutoTrainingSnapshotReadoutEntropyEvaluation",
    "AutoTrainingSnapshotRepeatedEvaluation",
    "AutoTrainingSnapshotTestEvaluation",
    "AutoTrainingConfig",
    "AutoTrainingResult",
    "CANONICAL_TENSOR_CONTRACT",
    "ClassicalCNN",
    "ClassicalMLP",
    "compute_histogram_shannon_entropy",
    "CrossEntropyLossCollector",
    "collect_error_analysis_payload",
    "configure_matplotlib_pdf_fonts",
    "ENCODER_NORMALIZATION_MISMATCH",
    "ErrorAnalysisPayload",
    "EvaluationSummary",
    "FiniteShotHistogram2D",
    "MetricHistorySummary",
    "TemporalStatisticSummary",
    "focus_metric_history",
    "format_nested_mapping_markdown",
    "FrqiEncoder2D",
    "ImageClassifierRunner",
    "LoadedAutoTrainingRun",
    "LoadedAutoTrainingRunEvaluationContext",
    "LoadedAutoTrainingRunTestEvaluation",
    "LoadedModelCheckpoint",
    "LossCollector",
    "MarginalMeasurement2D",
    "ModelSpec",
    "MnistDatasetConfig",
    "ModeMultiplexer2D",
    "MisclassifiedExample",
    "OptimizerConfig",
    "OutputConfig",
    "PCSQCNN",
    "PCSQCNNNoQFT",
    "PreparedMnistSplits",
    "RegisterLayout2D",
    "SeedConfig",
    "SeedTrainingArtifacts",
    "SeedTrainingRun",
    "StatisticBatchContext",
    "StatisticCollector",
    "TensorImageDataset",
    "TrainingHistory",
    "TrainingConfig",
    "accuracy_from_logits",
    "article_alignment_warnings",
    "evaluate_auto_training_snapshot_layer_gradient_norms_on_saved_mnist_test",
    "evaluate_auto_training_snapshot_batchwise_loss_sampling_on_saved_mnist_test",
    "evaluate_auto_training_snapshot_readout_entropy_on_saved_mnist_test",
    "evaluate_auto_training_snapshot_readout_landscape_on_saved_mnist_test",
    "evaluate_auto_training_snapshot_repeated_on_saved_mnist_test",
    "evaluate_auto_training_snapshot_on_saved_mnist_test",
    "evaluate_loaded_auto_training_run_on_saved_mnist_test",
    "is_power_of_two",
    "load_auto_training_run",
    "load_model_checkpoint",
    "load_saved_parameter_stats_line",
    "load_saved_training_histories",
    "move_active_qubit_to_condition",
    "pauli_coefficients_to_unitary",
    "plot_convergence",
    "plot_error_analysis",
    "plot_error_analysis_payload",
    "plot_temporal_summary",
    "prepare_mnist_splits",
    "reconstruct_auto_training_snapshot_runner_and_test_loader",
    "reconstruct_run_runner_and_test_loader",
    "reconstruct_saved_mnist_splits_from_run",
    "resolve_snapshot_trainable_layer_blocks",
    "run_mnist_auto_training",
    "save_model_checkpoint",
    "summarize_accuracy_histories",
    "summarize_temporal_samples",
    "warn_for_article_alignment",
]
